version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - echo Installing dependencies...
      - sudo apt update -y
  build:
    commands:
      - echo Building the application...
  post_build:
    commands:
      - echo Build completed successfully.
artifacts:
  files:
    - 'appspec.yml'
    - 'index.html'
    -  '**/*'
